### ISSUE TITLE
tutorial "tensorflow: static graphs" not working with tensorflow 2.0

### ISSUE THREAD

**Issue by andreipit** [pytorch/tutorials#672]
Tutorial [TENSORFLOW: STATIC GRAPHS](https://pytorch.org/tutorials/beginner/examples_autograd/tf_two_layer_net.html#sphx-glr-beginner-examples-autograd-tf-two-layer-net-py) not working with TensorFlow 2.0 RC.
AttributeError: module 'tensorflow' has no attribute 'placeholder'

Please make this tutorial compatible with the second version of TF.

**Comment by soumith** [comment]
@SethHWeidman looks like we have to delete that one :)

**Comment by SethHWeidman** [comment]
Hey @andreipit, thanks for bringing this up! We got rid of this outdated example - see #679.
