### ISSUE TITLE
Dynamic Quantization on BERT notebook - huggingface transformer version

### ISSUE THREAD

**Issue by lambdaofgod** [pytorch/tutorials#1114]
## 🐛 Bug

The notebook for [Dynamic Quantization on BERT ](https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html)  should use fixed version of huggingface/transformers, I've tried and it works with  `transformers==2.0.0`

Withouth this change it gives error in section 3.2:

`TypeError: glue_convert_examples_to_features() got an unexpected keyword argument 'pad_on_left'`

**Comment by TheMemoryDealer** [comment]
\assigntome
